version: '3'
services:
  client:
    container_name: phone_catalog_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - server
  server:
    container_name: phone_catalog_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    container_name: phone_catalog_db
    image: mongo
    ports:
      - '27018:27017'
