export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const LOAD_PHONES_SUCCESS = 'LOAD_PHONES_SUCCESS';
export const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS';
export const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS';
export const DELETE_PHONE_OPTIMISTIC = 'DELETE_PHONE_OPTIMISTIC';

export const LOAD_PHONE_SUCCESS = 'LOAD_PHONE_SUCCESS';
export const SET_PHONE = 'SET_PHONE';

export const SET_PHONES_FILTER = 'SET_PHONES_FILTER';
